BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[SMS] (
    [id] INT NOT NULL IDENTITY(1,1),
    [sender] NVARCHAR(1000) NOT NULL,
    [message] NVARCHAR(1000) NOT NULL,
    [isSent] BIT NOT NULL CONSTRAINT [SMS_isSent_df] DEFAULT 1,
    [timestamp] DATETIME2 NOT NULL CONSTRAINT [SMS_timestamp_df] DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT [SMS_pkey] PRIMARY KEY CLUSTERED ([id])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
