BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[Chat] (
    [id] INT NOT NULL IDENTITY(1,1),
    [chatID] NVARCHAR(1000) NOT NULL,
    [username] NVARCHAR(1000) NOT NULL,
    [socketID] NVARCHAR(1000) NOT NULL,
    [isActive] BIT NOT NULL CONSTRAINT [Chat_isActive_df] DEFAULT 1,
    CONSTRAINT [Chat_pkey] PRIMARY KEY CLUSTERED ([id]),
    CONSTRAINT [Chat_chatID_key] UNIQUE NONCLUSTERED ([chatID])
);

-- CreateTable
CREATE TABLE [dbo].[Message] (
    [id] INT NOT NULL IDENTITY(1,1),
    [chatID] NVARCHAR(1000) NOT NULL,
    [sender] NVARCHAR(1000) NOT NULL,
    [text] NVARCHAR(1000) NOT NULL,
    CONSTRAINT [Message_pkey] PRIMARY KEY CLUSTERED ([id])
);

-- AddForeignKey
ALTER TABLE [dbo].[Message] ADD CONSTRAINT [Message_chatID_fkey] FOREIGN KEY ([chatID]) REFERENCES [dbo].[Chat]([chatID]) ON DELETE NO ACTION ON UPDATE CASCADE;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
